local function axera_example(example_name, ...)
    target(example_name)
        set_kind("binary")
        add_files(...)
        add_includedirs(".")
        set_targetdir("$(builddir)/bin/ax620")
        set_installdir("$(builddir)/install")
        set_optimize("fastest")  -- use -O3
        add_packages("ax620", "opencv-arm-gnueabihf", "arm-gnueabihf")
    target_end()
end

axera_example("ax_classification", "ax_classification_steps.cc")
axera_example("ax_classification_nv12", "ax_classification_nv12_resize_steps.cc")
axera_example("ax_classification_nv12_opt", "ax_classification_nv12_resize_opt.cc")
axera_example("ax_yolov5s", "ax_yolov5s_steps.cc")
axera_example("ax_yolov5_lite", "ax_yolov5_lite_steps.cc")
axera_example("ax_yolov5s_face", "ax_yolov5s_face_steps.cc")
axera_example("ax_yolov5s_visdrone", "ax_yolov5s_visdrone_steps.cc")
axera_example("ax_yoloxs", "ax_yoloxs_steps.cc")
axera_example("ax_yolo_fastest", "ax_yolo_fastest_steps.cc")
axera_example("ax_yolo_fastest_body", "ax_yolo_fastest_body_steps.cc")
axera_example("ax_hrnet", "ax_hrnet_steps.cc")
axera_example("ax_hrnet_animal", "ax_hrnet_animal_steps.cc")
axera_example("ax_yolov3", "ax_yolov3_steps.cc")
axera_example("ax_yolov3_tiny", "ax_yolov3_tiny_steps.cc")
axera_example("ax_yolov4", "ax_yolov4_steps.cc")
axera_example("ax_yolov4_tiny", "ax_yolov4_tiny_steps.cc")
axera_example("ax_yolov4_tiny_3l", "ax_yolov4_tiny_3l_steps.cc")
axera_example("ax_nanodet", "ax_nanodet_steps.cc")
axera_example("ax_paddle_yolov3", "ax_paddle_yolov3_steps.cc")
axera_example("ax_scrfd", "ax_scrfd_steps.cc")
axera_example("ax_pose_ppl", "ax_pose_ppl_steps.cc")
axera_example("ax_yolov5s_license_plate", "ax_yolov5s_license_plate_steps.cc")

axera_example("ax_classification_accuracy", "ax_classification_accuracy.cc")
axera_example("ax_yolov3_accuracy", "ax_yolov3_accuracy.cc")

axera_example("ax_yolov5s_620u", "ax_yolov5s_620u_steps.cc")
axera_example("ax_robot_obstacle", "ax_robot_obstacle_detect_steps.cc")
axera_example("ax_yolov7", "ax_yolov7_steps.cc")
axera_example("ax_models_load_inspect", "ax_models_load_inspect.cc")
axera_example("ax_paddle_mobilehumseg", "ax_paddle_mobilehumseg_steps.cc")
axera_example("ax_monodlex", "ax_monodlex_steps.cc")
axera_example("ax_paddle_mobileseg", "ax_paddle_mobileseg.cc")
axera_example("ax_crnn", "ax_crnn_steps.cc")
axera_example("ax_face_parsing", "ax_face_parsing_steps.cc")
axera_example("ax_handpose", "ax_handpose_steps.cc")
axera_example("ax_yolov5s_seg", "ax_yolov5s_seg_steps.cc")
axera_example("ax_palm_detection", "ax_palm_detection_steps.cc")
axera_example("ax_yolopv2", "ax_yolopv2_steps.cc")
axera_example("ax_yolov7s_face", "ax_yolov7s_face_steps.cc")
axera_example("ax_yolov7s_palm", "ax_yolov7s_palm_steps.cc")
axera_example("ax_yolov6s", "ax_yolov6s_steps.cc")
axera_example("ax_yolov8s", "ax_yolov8s_steps.cc")
axera_example("ax_yolov8s_seg", "ax_yolov8s_seg_steps.cc")
axera_example("ax_yolov8s_pose", "ax_yolov8s_pose_steps.cc")

axera_example("ax_mmyoloxs", "mmyolo/ax_mmyoloxs.cc")
axera_example("ax_mmppyoloeps", "mmyolo/ax_mmppyoloeps.cc")
axera_example("ax_mmyolov6s", "mmyolo/ax_mmyolov6s.cc")

axera_example("ax_mmyolov8s", "mmyolo/ax_mmyolov8s.cc")
