name: Xmake build test

on:
  push:
    branches: [ "xmake" ]
  pull_request:
    branches: [ "xmake" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chip: ["ax650", "ax630c", "ax620q", "ax620"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with: 
          xmake-version: branch@master
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: 'xmake-20251208'
          # make it false due to unknown upstream error
          # package-cache: true
          # package-cache-key: 'xmake-20251208'  # we need to update this key when modifying pkg descriptions
          build-cache: true
          build-cache-key: 'xmake-${{ matrix.chip }}'

      - name: Configure xmake project
        run: xmake f -cvD --policies=build.ccache:y --chip=${{ matrix.chip }} --yes

      - name: Build xmake project
        run: |
          xmake build -vD --all
